window.sentlog=window.sentlog||{referrer:!1};window.site_name=window.site_name||"M58";window.page_type=window.page_type||"NA";window.post_count=window.post_count||-1;window.tgreg=window.tgreg||-1;window._trackURL=window._trackURL||"NA";window._trackParams=window._trackParams||"NA";var referrer=encodeURIComponent(document.referrer),json_sid="NA";"undefined"!=typeof ____json4fe&&"sid"in ____json4fe&&(json_sid=____json4fe.sid);var pagetypeTmp,post_countTmp,cateTmp="",areaTmp="",GA_pageviewTmp="";
if("NA"!=_trackURL){var trackJsonStr=eval("("+_trackURL+")");trackJsonStr.pagetype&&(pagetypeTmp=trackJsonStr.pagetype);trackJsonStr.post_count&&(post_countTmp=trackJsonStr.post_count);trackJsonStr.cate&&(cateTmp=trackJsonStr.cate);trackJsonStr.area&&(areaTmp=trackJsonStr.area);trackJsonStr.GA_pageview&&(GA_pageviewTmp=trackJsonStr.GA_pageview)}window.page_type=window.page_type||pagetypeTmp||"NA";window.post_count=window.post_count||post_countTmp||-1;window._gaq=window._gaq||[];
var GTID=Math.random(),GTID=(new Date).valueOf()+""+GTID;"NA"!=json_sid&&""!=json_sid&&(GTID=json_sid);var ClickID=1,curURL=window.location.href;if("NA"==_trackURL)_trackURL="{'GTID':'"+GTID+"'}";else{var tmpArr=_trackURL.split("{");_trackURL=tmpArr[0]+"{'GTID':'"+GTID+"',"+tmpArr[1]}
window.$&&($("[tongji_id]").bind("click",function(a){var b=a.srcElement?a.srcElement:a.target;"A"==b.tagName.toUpperCase()&&(a=$(b).attr("href")||"#",b=$(b).text(),-1==a.indexOf("javascript:")&&"#"!=a.substring(0,1)&&clickLog("from="+$(this).attr("tongji_id")+"&text="+encodeURIComponent(b)+"&to="+encodeURIComponent(a)))}),function(){$("[tongji_tag]").bind("click",function(){var a=$(this).attr("tongji_tag");clickLog("from="+a)})}(),function(){-1!=(_trackURL||"NA").indexOf("'pagetype':'home'")&&$("[href]").bind("click",
function(a){var b=$(this).attr("href"),c=$(this).offset().top,e=$(this).offset().left;clickLog("from=heatmap:"+b+"&tagX="+e+"&tagY="+c+"&mouseX="+a.pageX+"&mouseY="+a.pageY)})}(),$("a").bind("click",function(){var a=ClickID;if("NO"==filterList(curURL)&&-1!=curURL.indexOf(".58.com")){var b=$(this).attr("href")||"#";-1!=b.indexOf("javascript:")||"#"==b.substring(0,1)||"NO"!=filterList(b)||"/"!=b.substring(0,1)&&-1==b.indexOf(".58.com")||(b.match(/[\?&]PGTID=[^&]*&ClickID=\d*/)?$(this).attr("href",b.replace(/PGTID=[^&]*&ClickID=\d*/,
"PGTID="+GTID+"&ClickID="+a)):$(this).attr("href",$.trim(b)+(-1==b.indexOf("?")?"?":"&")+"PGTID="+GTID+"&ClickID="+a))}}));var logmsg_bak="";
if(!sentlog.referrer){_trackParams=format_trackParams(_trackParams);_trackParams=encodeURIComponent(_trackParams);var logmsg="tag=pvstatall&referrer="+referrer+"&type="+page_type+"&post_count="+post_count+"&_trackParams="+_trackParams;if("detail"==page_type)try{logmsg=logmsg+"&userid="+____json4fe.userid,"phone"in ____json4fe&&(logmsg=logmsg+"&huzhuan="+____json4fe.phone),0<tgreg&&(logmsg=logmsg+"&tgreg="+tgreg)}catch(e$$14){}try{if("version"in ____json4fe&&(logmsg=logmsg+"&version="+____json4fe.version),
"smsc"in ____json4fe&&(logmsg=logmsg+"&smsc="+____json4fe.smsc),"start"in ____json4fe&&(logmsg+="&loadtime="+((new Date).getTime()-____json4fe.start)),"supplycount"in ____json4fe)for(var attr in ____json4fe.supplycount)logmsg=logmsg+"&supplycount."+attr+"="+____json4fe.supplycount[attr]}catch(e$$15){}try{logmsg=logmsg+"&window_size="+document.documentElement.clientWidth+"x"+document.documentElement.clientHeight}catch(e$$16){}try{var m_ga_utma=getcookie("__utma");m_ga_utma&&""!=m_ga_utma&&(logmsg=
logmsg+"&_ga_utma="+m_ga_utma);var cookie_utm_source=getcookie("utm_source")||"",cookie_utm_campaign=getcookie("utm_campaign")||"",cookie_spm=getcookie("spm")||"";"NA"!=_trackURL?(tmpArr=_trackURL.split("{"),_trackURL=tmpArr[0]+"{'utm_source':'"+cookie_utm_source+"',"+tmpArr[1]):_trackURL="{'utm_source':'"+cookie_utm_source+"'}";logmsg=logmsg+"&utm_source="+cookie_utm_source;"NA"!=_trackURL?(tmpArr=_trackURL.split("{"),_trackURL=tmpArr[0]+"{'utm_campaign':'"+cookie_utm_campaign+"',"+tmpArr[1]):_trackURL=
"{'utm_campaign':'"+cookie_utm_campaign+"'}";"NA"!=_trackURL?(tmpArr=_trackURL.split("{"),_trackURL=tmpArr[0]+"{'spm':'"+cookie_spm+"',"+tmpArr[1]):_trackURL="{'spm':'"+cookie_spm+"'}";var init_refer=referrer,cookie_init_refer=getcookie("init_refer"),cookie_new_session=getcookie("new_session");cookie_new_session&&""!=cookie_new_session?(setcookie_session("new_session","0"),setcookie_session("init_refer",cookie_init_refer),"NA"!=_trackURL?(tmpArr=_trackURL.split("{"),_trackURL=tmpArr[0]+"{'new_session':'0','init_refer':'"+
cookie_init_refer+"',"+tmpArr[1]):_trackURL="{'new_session':'0','init_refer':'"+cookie_init_refer+"'}"):(setcookie_session("new_session","1"),setcookie_session("init_refer",init_refer),"NA"!=_trackURL?(tmpArr=_trackURL.split("{"),_trackURL=tmpArr[0]+"{'new_session':'1','init_refer':'"+init_refer+"',"+tmpArr[1]):_trackURL="{'new_session':'1','init_refer':'"+init_refer+"'}");var cookie_new_uv=getcookie("new_uv");cookie_new_uv&&""!=cookie_new_uv?cookie_new_session&&""!=cookie_new_session||cookie_new_uv++:
cookie_new_uv=1;setcookie("new_uv",cookie_new_uv,365);"NA"!=_trackURL?(tmpArr=_trackURL.split("{"),_trackURL=tmpArr[0]+"{'new_uv':'"+cookie_new_uv+"',"+tmpArr[1]):_trackURL="{'new_uv':'"+cookie_new_uv+"'}"}catch(e$$17){}"NA"!=_trackURL&&(logmsg=logmsg+"&trackURL="+_trackURL);logmsg_bak=logmsg;ajaxlog_new(logmsg);"NA"!=_trackURL&&"NA"!=pagetypeTmp&&"list"==pagetypeTmp&&ajaxlog_mlistshow(_trackURL)}
function setcookie(a,b,c){var e=new Date;e.setTime(e.getTime()+864E5*c);document.cookie=a+"="+escape(b)+"; expires="+e.toGMTString()+"; domain=.58.com; path=/"}function setcookie_session(a,b){var c=new Date;c.setTime(c.getTime()+18E5);document.cookie=a+"="+escape(b)+"; expires="+c.toGMTString()+"; domain=.58.com; path=/"}function getcookie(a){var b;return(b=document.cookie.match(RegExp("(^| )"+a+"=([^;]*)(;|$)")))?unescape(b[2]):""}function ajaxsend(a){(new Image).src=a}
function ajaxlog_new(a){var b=Math.random();ajaxsend(document.location.protocol+"//tracklog1.58.com/m/empty.js.gif?site_name="+site_name+"&"+a+"&rand_id="+b);var c=_trackURL||"NA";if(-1!=c.indexOf("'pagetype':'detail'")||-1!=c.indexOf("'pagetype':'jianli_detail'"))-1==c.indexOf("'cate':'9224")&&-1==c.indexOf("'cate':'9225")&&-1==c.indexOf("'cate':'13941")&&-1==c.indexOf("'cate':'13952")||ajaxsend(document.location.protocol+"//dialog.58.com/transfer?DIATag=MTrack&"+a+"&rand_id="+b);"list"==pagetypeTmp&&
ajaxsend(document.location.protocol+"//gdt.cm.58.com/gdtcm?city="+areaTmp+"&cate="+cateTmp+"&plat=M")}function format_trackParams(a){if("NA"==a)return a;try{for(var b=[],c=0,e=a.length;c<e;c++)b.push(a[c].I+":"+a[c].V.replace(/\|/g,"*"));return b.join("@@")}catch(d){return"error"}}function loadMorePage(a){var b=Math.random();ajaxsend(document.location.protocol+"//tracklog1.58.com/m/empty.js.gif?site_name="+site_name+"&"+(logmsg_bak+"&EventTag=loadMorePage&"+a)+"&rand_id="+b)}
function clickLog(a){var b=ClickID,c=getcookie("bangbangid");c&&""!=c||(c="");ajaxsend(document.location.protocol+"//tracklog1.58.com/m/click/empty.js.gif?site_name="+site_name+"&tag=pvsiters&"+a+"&trackURL="+_trackURL+"&ClickID="+b+"&bangbangid="+c+"&referrer="+referrer+"&rand="+Math.random());ajaxsend(document.location.protocol+"//tracklog1.58.com/Mv1/click/empty.js.gif?site_name="+site_name+"&tag=mclick&"+a+"&trackURL="+_trackURL+"&ClickID="+b+"&bangbangid="+c+"&referrer="+referrer+"&rand="+Math.random());
-1!=a.indexOf("&ROI=")&&ajaxsend(document.location.protocol+"//dialog.58.com/transfer?DIATag=MClick&"+a+"&trackURL="+_trackURL+"&ClickID="+b+"&bangbangid="+c+"&referrer="+referrer+"&rand="+Math.random());setTimeout("ClickIDPlus()",300)}
function listClickLog(a){var b=ClickID,c=getcookie("bangbangid");c&&""!=c||(c="");ajaxsend(document.location.protocol+"//tracklog1.58.com/m/click/empty.js.gif?tag=mlistclick&"+a+"&trackURL="+_trackURL+"&ClickID="+b+"&bangbangid="+c+"&referrer="+referrer+"&rand="+Math.random());setTimeout("ClickIDPlus()",300)}
function filterList(a){var b=".58.com.cn portal.58.com faw-vw-dasweltauto.58.com 5858.com lieche.58.com dict.58.com/xiaoqu about.58.com m.58.com/city.html".split(" "),c;for(c in b)if(-1!=a.indexOf(b[c]))return"YES";return"NO"}function showLog(a){}function ClickIDPlus(){ClickID+=1}
function ajaxlogr(a){ajaxsend(document.location.protocol+"//tracklog1.58.com/m/click/empty.js.gif?site_name="+site_name+"&"+a+"&trackURL="+_trackURL+"&ClickID="+ClickID+"&referrer="+referrer+"&rand="+Math.random());setTimeout("ClickIDPlus()",300)}
function ajaxlog_mlistshow(){try{if(window.$){var a=Math.random(),b=getcookie("bangbangid");b&&""!=b||(b="");var c="",c="NA"!=cateTmp?cateTmp.split(",")[0]:"",e=[];$("li[infoid]").each(function(){var a=$(this),b=a.attr("logr");if(b)if("9224"==c||"13941"==c){var b=a.attr("_pos"),d=a.attr("pos"),h=a.attr("sortid"),l=a.attr("logr"),m=[],k="";l&&(a=a.attr("logr").split("_"),m.push(a[0],a[1],a[2],a[3]),l=a[a.length-1],(l=l.replace("ses^","ses:"))&&(k+=l));h&&(k+="@sortid:"+h);b&&(k+="@npos:"+b);d&&(k+=
"@pos:"+d);""!=k&&m.push(k);e.push(m.join("_"))}else b&&(b=b.replace("ses^","ses:")),(d=a.attr("pos"))&&(b+="@pos:"+d),e.push(b);else d=a.attr("post_type"),b=a.attr("enum_user"),h=a.attr("uid"),a=a.attr("infoid"),b=d+"_"+b+"_"+h+"_"+a,a&&(d=$("[infoid]").index($(this))+1,b+="_@pos:"+d),e.push(b)});ajaxsend(document.location.protocol+"//tracklog1.58.com/Mv1/listshow/empty.js.gif?tag=mlistshow&fromid=referrer_m&bangbangid="+b+"&referrer="+referrer+"&site_name="+site_name+"&info_data="+e.join(",")+"&trackURL="+
_trackURL+"&rand_id="+a)}}catch(d){ajaxsend(document.location.protocol+"//tracklog1.58.com/Mv1/listshow/empty.js.gif?tag=mlistshow&fromid=referrer_m&Error="+d)}}
if(window.$)try{(function(){$("li[infoid]").bind("click",function(){var a=Math.random(),b=ClickID,c=getcookie("bangbangid");c&&""!=c||(c="");var e="",e="NA"!=cateTmp?cateTmp.split(",")[0]:"",d=$(this);"li"!==d[0].tagName.toLowerCase()&&(d=d.parent());var g=d.attr("logr"),f="",f="";if(g)if("9224"==e||"13941"==e){var g=d.attr("_pos"),e=d.attr("pos"),n=d.attr("sortid"),h=d.attr("logr"),l=[];h&&(d=d.attr("logr").split("_"),l.push(d[0],d[1],d[2],d[3]),h=d[d.length-1],(h=h.replace("ses^","ses:"))&&(f+=
h));n&&(f+="@sortid:"+n);g&&(f+="@npos:"+g);e&&(f+="@pos:"+e);""!=f&&l.push(f);f=l.join("_")}else g&&(g=g.replace("ses^","ses:")),(e=d.attr("pos"))&&(g+="@pos:"+e),f=g;else f=d.attr("post_type"),e=d.attr("enum_user"),g=d.attr("uid"),d=d.attr("infoid"),f=f+"_"+e+"_"+g+"_"+d,d&&(e=$("[infoid]").index($(this))+1,f+="_@pos:"+e);ajaxsend(document.location.protocol+"//tracklog1.58.com/Mv1/listclick/empty.js.gif?tag=mlistclick&fromid=referrer_m&bangbangid="+c+"&referrer="+referrer+"&site_name="+site_name+
"&info_data="+f+"&trackURL="+_trackURL+"&ClickID="+b+"&rand_id="+a);setTimeout("ClickIDPlus()",300)})})()}catch(e$$20){ajaxsend(document.location.protocol+"//tracklog1.58.com/Mv1/listclick/empty.js.gif?tag=mlistclick&fromid=referrer_m&Error="+e$$20)};
