window.jobcn||(window.jobcn={});jobcn.pkg=function(arg1,arg2,arg3){var context,namespace,method;if(arguments.length==3)
{context=arg1;namespace=arg2;method=arg3;}else{context=window;namespace=arg1;method=arg2;}
if(!namespace||!namespace.length){return null}
var a=namespace.split(".");for(var c=context,f=0;f<a["length"]-1;f++){c[a[f]]||(c[a[f]]={});c=c[a[f]];}
c=(c[a[a["length"]-1]]=method||c[a[a["length"]-1]]||{});return c;};jobcn.Cache={_cache:{},_size:0,set:function(key,defaultValue){if(!jobcn.Cache.contains(key))jobcn.Cache._size++;jobcn.Cache._cache[key]=defaultValue;return defaultValue;},get:function(key,_function){var self=jobcn.Cache;var u=self._cache[key];if(u){return u;}
if(typeof(_function)=="function")
{u=_function();self._cache[key]=u;}else if(_function){u=_function;self._cache[key]=u;}else{u=jQuery(key);self._cache[key]=u;}
self._size++;return u;},remove:function(key){jobcn.Cache._size--;jobcn.Cache._cache[key]=null;},contains:function(key){return jobcn.Cache._cache[key];}};(function(){var swf_id="jobcn_storage";var localStorage=false;try{localStorage=window.localStorage;}catch(e){}
var supports_local_storage=!!localStorage;var doc=document;var obj;var initStorage=(supports_local_storage?false:function(swfPath)
{log("jobcn.Storage","init");var swf_path=swfPath+"?t="+new Date().getTime();var html=jobcn.isIE?'<object classid="clsid:d27cdb6e-ae6d-11cf-96b8-444553540000" codebase="http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=10,0,0,0" width="1" height="1" id="'+swf_id+'" align="middle"><param name="allowScriptAccess" value="sameDomain" /><param name="allowFullScreen" value="false" /><param name="movie" value="'+swf_path+'" /><param name="quality" value="high" /><param name="bgcolor" value="#ffffff" /></object>':'<embed src="'+swf_path+'" quality="high" bgcolor="#ffffff" width="1" height="1" id="'+swf_id+'" align="middle" allowScriptAccess="always" allowFullScreen="false" type="application/x-shockwave-flash" pluginspage="http://www.adobe.com/go/getflashplayer_cn" />';var div=doc.createElement('div');div.style.width="1px";div.style.height="1px";div.style.overflow="hidden";div.style.position="absolute";div.style.top="0";div.style.right="0";doc.body.insertBefore(div,doc.body.childNodes[0]);div.innerHTML=html;});jobcn.Storage=function(id){var self=this;this.obj=null;this.id=null;this.init(this.id);};jobcn.Storage.prototype={swfPath:"/public/script/jobcn95/storage.swf",init:function(id){this.id=id||"default";if(initStorage){initStorage(this.swfPath);initStorage=false;}},_getObj:function(){if(!this.obj){if(supports_local_storage)
{this.obj={set:function(id,name,value){this.remove(id,name);localStorage.setItem(name,jobcn.lang.json.stringify(value));},get:function(id,name){var v=localStorage.getItem(name);if(v)v=jobcn.lang.json.parse(v);return v||"";},append:function(id,name,value){this.set(name,this.get(name)+value);},remove:function(id,name){localStorage.removeItem(name);},clear:function(id){localStorage.clear();}};}else{this.obj=doc.getElementById(swf_id);}}
return this.obj;},set:function(name,value){this._getObj().set(this.id,name,value);},append:function(name,value){this._getObj().append(this.id,name,value);},get:function(name){return this._getObj().get(this.id,name);},remove:function(name)
{this._getObj().remove(this.id,name);},clear:function(){return this._getObj().clear(this.id);},setMaxSize:function(num)
{this._getObj().setMaxSize(num);},isReady:function(){return this._getObj()&&this._getObj().get;}};})();jobcn.Plugin={if_jquery:function(fun,retryTime){try{var thix=arguments.callee;retryTime=retryTime||2;if(typeof(jQuery)!="undefined")
{fun(jQuery);}else{if(retryTime==0)return;setTimeout(function(){thix(fun,retryTime-1);},1000);}}catch(e){if(jobcn.debug)throw e;}},if_jsapi:function(fun){try{if(typeof(ol)!="undefined"&&typeof(ol.loader)!="undefined")
{fun(ol);}}catch(e){if(jobcn.debug)throw e;}}};if(jobcn.isIE6){try{document.execCommand("BackgroundImageCache",false,true);}catch(e){}}
(function(){var _jt=jobcn.template=function(_template){this.init=function(){_template=_separateTemplate(_template);var tmp;for(var i=0;i<_template.length;i++)
{tmp=_renderTemplate(_template[i]);_cache[tmp[0]]=_parseTemplate(tmp);}};this.parse=function(template,data)
{if(!template||!(template=_cache[template]))return"";return _parseData(template,data);};this.init();};_jt.parse=function(template,data){var x=_parseData(_parseTemplate(_renderTemplate(template)),data);return x;};_jt.startDelimiter="<!--";_jt.endDelimiter="-->";var _cache={},_separateTemplate_re=new RegExp(_jt.startDelimiter+"#macro \\S+\\s*\\w*"+_jt.endDelimiter+"[\\s\\S]*?"+_jt.startDelimiter+"/#macro"+_jt.endDelimiter,"g"),_separateTemplate=function(_template){return _template.match(_separateTemplate_re);},_renderTemplate_re=new RegExp("("+_jt.startDelimiter+"(\/?)#([\\s\\S]*?)"+_jt.endDelimiter+")|(\')|([\r\n\t])|(\{#([^\}]*?)\})","g"),_renderTemplate=function(_template){var template=_template.replace(_renderTemplate_re,function(a,b,c,d,e,f,g,h){if(b){return'\n'+(c?'-':'+')+d.replace(/[\r\n\t]/g,"")+'\n';}
if(e){return'\\\'';}
if(f){return'';}
if(g){return"'+("+h.replace(/\\'/g,'\'')+")+'";}});template=template.split(/\n/);var t,tmp,command,templateName,dataName,reStr=["var f=[];"];for(var i=0;i<template.length;i++)
{t=template[i];if(!t){continue;}
tmp=t.charAt(0);if(tmp!=='+'&&tmp!=='-'){reStr.push("f.push('"+t+"');");continue;}
command=t.split(/\s/);switch(command[0])
{case'+macro':templateName=command[1];dataName=command[2];reStr.push('f.push("<!--'+templateName+' start--\>");');break;case'-macro':reStr.push('f.push("<!--'+templateName+' end--\>");');break;case'+elseif':command.splice(0,1);reStr.push('}else if'+command.join(' ')+'{');break;case'+else':reStr.push('}else{');break;case'+if':case'+for':case"+switch":command[0]=command[0].substr(1);reStr.push(command.join(' ')+'{');break;case"+case":case"+default":command[0]=command[0].substr(1);reStr.push(command.join(' ')+':');break;case"-switch":case'-for':case'-if':reStr.push('}');break;case'+list':if(command.length!=4)
{throw templateName+": list command error!";}
var _index=command[3]+'_index';var _length=command[3]+'_length';reStr.push('if('+command[1]+'.constructor === Array){');reStr.push('var '+command[3]+';');reStr.push('var '+_length+'='+command[1]+'.length;');reStr.push('var '+_index+';');reStr.push('for(var _$_i='+_length+';_$_i--;){');reStr.push(_index+'='+_length+'-_$_i-1;');reStr.push(command[3]+'='+command[1]+'['+_index+'];');break;case'-list':reStr.push('}}');break;case"+break":reStr.push('break;');break;case'-list':reStr.push('}}}');break;case'+eval':command.splice(0,1);reStr.push(command.join(' '));break;case'+var':command[0]=command[0].substr(1);reStr.push(command.join(' ')+';');break;default:break;}}
reStr.push("return f.join('');");return[templateName,dataName||"data",reStr.join("")];},_parseTemplate=function(_template){try{return new Function(_template[1],_template[2]);}catch(e){logger.error("template:"+_template[0],e);}},_parseData=function(_function,data){return _function(data);};})();jobcn.pkg("jobcn.ui");(function(){var resize_function=function(){var css={};css.width=jobcn.ui.masker._bwidth;css.height=jobcn.ui.masker._bheight;jobcn.Cache.get("jobcn_mask").css(css);};var _default={css:{opacity:0.2,background:"#000"}};jobcn.ui.masker={isShown:false,mask:function(options){var $=jQuery;var thix=jobcn.ui.masker;if(thix.isShown)return;options=$.extend(true,{},_default,options);var mask=jobcn.Cache.get("jobcn_mask",function(){$(window).resize(function(){if(jobcn.ui.masker.isShown)return;jobcn.Cache.get("jobcn_mask").css({width:thix._bwidth(),height:thix._bheight()});});return $("<div id='jobcn_mask' class='jobcn_mask'></div>").appendTo('body').bgiframe();});thix.isShown=true;options.css.width=thix._bwidth();options.css.height=thix._bheight();options.css.visibility="visible";mask.css(options.css);$(window).bind("resize",resize_function);},unmask:function(){jobcn.ui.masker.isShown=false;jobcn.Cache.get("jobcn_mask").css({visibility:"hidden",width:0,height:0});jQuery(window).unbind("resize",resize_function);},_bheight:function(){var $=jQuery;if($.browser.msie&&$.browser.version<7){var scrollHeight=Math.max(document.documentElement.scrollHeight,document.body.scrollHeight);var offsetHeight=Math.max(document.documentElement.offsetHeight,document.body.offsetHeight);if(scrollHeight<offsetHeight){return $(window).height();}else{return scrollHeight;}}else{return $(document).height();}},_bwidth:function(){var $=jQuery;if($.browser.msie&&$.browser.version<7){var scrollWidth=Math.max(document.documentElement.scrollWidth,document.body.scrollWidth);var offsetWidth=Math.max(document.documentElement.offsetWidth,document.body.offsetWidth);if(scrollWidth<offsetWidth){return $(window).width();}else{return scrollWidth;}}else{return $(document.body).width();}}};})();(function(){var _default={event:"hover",menu:null};jobcn.ui.dropdown=function(selector,options)
{var self=this;self.hideTimer=null;self._objItem;self._menuItem;self._onMenu=false;self._events={};self._isShow=false;self._hideMenu=function()
{self.hideTimer=setTimeout(self.hide,100);}
self.init=function(){var $=jQuery;options=$.extend({},_default,options);if(options.event=="hover")options.event="mouseover";else options.event="click";self._objItem=$(selector);self._menuItem=options.menu?$(options.menu):self._objItem.next();self._objItem.unbind(options.event).bind(options.event,function(v){clearTimeout(self.hideTimer);self.show();});self._menuItem.find(".dropdown_item").bind("click",function(){setTimeout(self.hide);});}
self.bind=function(selector,action,fun){self._menuItem.find(selector).bind(action,fun);}
self.show=function(){switch(options.event)
{case"mouseover":self._objItem.unbind("mouseout").bind("mouseout",function(v){self._hideMenu();self._objItem.addClass("hover");});self._menuItem.unbind("mouseover").bind("mouseover",function(){clearTimeout(self.hideTimer);self._menuItem.css("display","block");}).unbind("mouseout").bind("mouseout",function(){self._hideMenu();});break;case"click":if(self._isShow){self.hide();return;}else{self._events["menu_click"]=function(){self._onMenu=true;};self._events["document_click"]=function(event){if(event.button!=0)return true;if(self._onMenu===false)
{self.hide();}
self._onMenu=false;};setTimeout(function(){self._menuItem.bind("click",self._events["menu_click"]);jQuery(document).bind("click",self._events["document_click"]);},1);}
break;}
self._objItem.addClass("hover");self._menuItem.css("display","block");self._isShow=true;}
self.hide=function(){if(self._events["document_click"])jQuery(document).unbind("click",self._events["document_click"]);if(self._events["menu_click"])self._menuItem.unbind("click",self._events["menu_click"]);self._objItem.removeClass("hover");self._menuItem.hide();self._isShow=false;self._onMenu=false;}
this.init();};})();jobcn.ui.scrollTo=function(target,options){options=options||{offsetY:0}
if(typeof(target)!="object")
{var c=target.toString().substr(0,1);if(!(c=="#"||c=="."))
{target="#"+target;}
target=jQuery(target);}
if(target.length==0)return;var objTop=target.offset().top;var doc=(document.documentElement&&!/webkit/ig.test(navigator.userAgent)?document.documentElement:document.body);var w_h=jQuery(window).height();var docTop=doc.scrollTop;if(!(docTop<objTop&&objTop<docTop+w_h))doc.scrollTop=objTop-options.offsetY;};(function(){var styles={"white":{opacity:0.55,background:"#fff"},"black":{opacity:0.2,background:"#000"}};var _default={selector:"#jobcn_ui_loading",css:null,modal:true,maskConfig:null};jobcn.ui.loading={options:null,show:function(options)
{var thix=jobcn.ui.loading;if(typeof(options)=="string")
{options={maskConfig:{css:styles[options]}};}
thix.options=jQuery.extend(true,{},_default,options);if(thix.options.modal)jobcn.ui.masker.mask(thix.options.maskConfig);var mask=jQuery(thix.options.selector);if(mask.length==0){mask=jQuery('<div id="jobcn_ui_loading" class="jobcn_ui_loading"></div>').appendTo("body");}
mask.css(thix.options.css);if(jobcn.isIE6||jobcn.isIE&&document.compatMode==="BackCompat")
{var win=jQuery(window),pTop=win.scrollTop(),pLeft=win.scrollLeft();pTop+=(win.height()-mask.height())/2;pLeft+=(win.width()-mask.width())/2;mask.css({top:pTop,left:pLeft});}
mask.show();mask=null;thix=null;},hide:function(){var opt=jobcn.ui.loading.options;if(opt)
{if(opt.modal)jobcn.ui.masker.unmask();jQuery(opt.selector).hide();}}};})();(function(){var _default={row:"tr",colors:["#fff",'#f7f7f7'],hover:"#e3f3bf",index:1,remain:0,alterNum:1};jobcn.ui.alternation=function(selector,options){var $=jQuery;function _alternation(obj,options)
{var self=this;this.container=$(obj);this.data={};this.rows=null;this.init=function(){this.rows=this.container.find(options.row);var row;var group;for(var i=0;i<this.rows.length;i++)
{row=this.rows[i];row.setAttribute("alternation",i);group=row.getAttribute("group");this.data[i]={group:group,backgroundColor:""};}}
this.bindColor=function(){if(!options.colors)return;var end=this.rows.length-options.remain;for(var i=options.index;i<end;)
{for(var j=0;j<options.colors.length&&i<end;j++)
{row=this.rows[i];row.style.backgroundColor=options.colors[j];this.data[i].backgroundColor=options.colors[j];i=i+options.alterNum;}}}
this.bindEvent=function(){this.rows.unbind("mouseover").bind("mouseover",function(){var thix=$(this);var index=thix.attr("alternation");var row=self.data[index];if(options.hover)thix.css("backgroundColor",options.hover);if(row.group)self.container.find(options.row+"[group="+row.group+"]").addClass("hover");}).unbind("mouseout").bind("mouseout",function(){var thix=$(this);var index=thix.attr("alternation");var row=self.data[index];if(options.hover)thix.css("backgroundColor",row.backgroundColor);if(row.group)self.container.find(options.row+"[group="+row.group+"]").removeClass("hover");});}
this.init();this.bindColor();this.bindEvent();}
options=$.extend({},_default,options);$(selector).each(function(){new _alternation(this,options);});}})();(function(){var _highlight=function(node,re,nodeName,className){if(node.nodeType===3){var match=node.data.match(re);if(match){var highlight=document.createElement(nodeName||'span');highlight.className=className||'jobcn_ui_highlight highlight';var wordNode=node.splitText(match.index);wordNode.splitText(match[0].length);var wordClone=wordNode.cloneNode(true);highlight.appendChild(wordClone);wordNode.parentNode.replaceChild(highlight,wordNode);return 1;}}else if((node.nodeType===1&&node.childNodes)&&!/(script|style)/i.test(node.tagName)&&!(node.tagName===nodeName.toUpperCase()&&node.className===className)){for(var i=0;i<node.childNodes.length;i++){i+=_highlight(node.childNodes[i],re,nodeName,className);}}
return 0;}
jobcn.ui.highlight=function(idOrClass,words,options)
{var settings={className:null,element:'span',caseSensitive:false,wordsOnly:false};jQuery.extend(settings,options);if(words.constructor===String){words=[words];}
words=jQuery.grep(words,function(word,i){return word!='';});if(words.length==0){return this;};var str=words.join("|");str=str.replace(/([\\\$\{\}\(\)\[\]\+\?\-\>\<\^\!\.\*])/g,"\\$1");var flag=settings.caseSensitive?"":"i";var pattern="("+str+")";if(settings.wordsOnly){pattern="\\b"+pattern+"\\b";}
var re=new RegExp(pattern,flag);var obj=idOrClass;if(typeof(idOrClass)=="string"){obj=jobcn.Cache.get(idOrClass)}
return obj.each(function(){_highlight(this,re,settings.element,settings.className);});}})();(function(){var data={"_jobcn_ui_alert":{_default:{title:"操作提示",zIndex:399,showCancel:false,modal:false,draggable:false,focus:".box-ok:first",width:300,clickOut:function(box){box.close();}}},"_jobcn_ui_info":{},"_jobcn_ui_warn":{},"_jobcn_ui_error":{}};function show(msg,options,options2){var C$=jobcn.Cache.get;var _dialog=C$(options.boxid,function(){return new ol.box(null,options);})
_dialog.open(msg);if(options2.timeout)
{if(data[options.boxid].timer)clearTimeout(data[options.boxid].timer);data[options.boxid].timer=setTimeout(function(){if(jobcn.isIE6)_dialog.close();else _dialog.fadeOut(800);},options2.timeout);C$("#"+options.boxid).unbind("mouseover").bind("mouseover",function(){clearTimeout(data[options.boxid].timer);}).unbind("mouseout").bind("mouseout",function(){data[options.boxid].timer=setTimeout(function(){if(jobcn.isIE6)_dialog.close();else _dialog.fadeOut(800);},options2.timeout/2);});}};var _default={title:"操作提示",zIndex:399,showButton:false,modal:false,draggable:false,focus:".box-close",width:300};jobcn.ui.warn=function(msg,options){options=jQuery.extend({},_default,options);options.boxid="_jobcn_ui_warn";options.boxclass="jobcn_ui_warn";var options2={timeout:options.timeout};delete options.timeout;show(msg,options,options2);};jobcn.ui.info=function(msg,options){options=jQuery.extend({},_default,options);options.boxid="_jobcn_ui_info";options.boxclass="jobcn_ui_info";var options2={timeout:options.timeout};delete options.timeout;show(msg,options,options2);};jobcn.ui.error=function(msg,options){options=jQuery.extend({},_default,options);options.boxid="_jobcn_ui_error";options.boxclass="jobcn_ui_error";var options2={timeout:options.timeout};delete options.timeout;show(msg,options,options2);};jobcn.ui.alert=function(msg,options){options=jQuery.extend({},data["_jobcn_ui_alert"]._default,options);options.boxid="_jobcn_ui_alert";options.boxclass="jobcn_ui_alert";var _dialog=jobcn.Cache.get(options.boxid,function(){return new ol.box(null,options);});_dialog.setTitle(options.title);_dialog.open(msg);};})();(function(){var _default={style:"style1",offsetX:0,offsetY:0},content='<div class="jobcn_ui_ballon"><div id="ballon_header"></div><div id="ballon_body"></div><div id="ballon_footer"></div></div>';jobcn.ui.ballon=function(selector,msg,options)
{options=jQuery.extend({},_default,options);var relativeObj=jQuery(selector);var _tips=jQuery(content);var _timer;_tips.find("#ballon_body").html(msg||"");relativeObj.mouseover(function(){_timer=setTimeout(function(){var offsetX=options.offsetX||0;var offsetY=options.offsetY||0;var top=relativeObj.offset().top+relativeObj.height();var left=relativeObj.offset().left;left=Math.max(left+offsetX,0);top=Math.max(top+offsetY,0);_tips.css({display:"block",top:top,left:left}).addClass(options.style);_tips.appendTo("body").bgiframe();},250);}).mouseout(function(){clearTimeout(_timer);_tips.remove();});return jobcn.ui;}})();(function(){var _default={css:null,captureInput:false};jobcn.ui.hover=function(idOrClass,options){var $=jQuery;options=$.extend(true,{},_default,options);$(idOrClass).each(function(){var old_css=null;var isFocus=false;var isMouseOver=false;var thix=$(this);var hover=function(){if(isFocus||isMouseOver)return;if(options.css)
{old_css=thix.attr("style");thix.css(options.css);}else thix.addClass("hover");};var unhover=function(){if(isFocus||isMouseOver)return;if(options.css)
{thix.attr("style",old_css);}else thix.removeClass("hover");};thix.mouseover(function(){hover();isMouseOver=true;}).mouseout(function(){isMouseOver=false;unhover()});if(this.tagName=="INPUT"||this.tagName=="TEXTAREA")
{thix.focus(function(){hover();isFocus=true;}).blur(function(){isFocus=false;unhover();});}else if(options.captureInput){thix.find("input[type=text],textarea").bind("focus",function(){hover();isFocus=true;}).bind("blur",function(){isFocus=false;unhover();});}});return jobcn.ui;}})();jobcn.pkg("jobcn.util");jobcn.util.trim=function(str){if(str==null)return"";if(typeof(str)!="string")return str;return str.trim();};jobcn.util.left=function(str,len,text){if(str.len()<len)return str;var strlen=0;for(var i=0;i<str.length;i++){if(str.charCodeAt(i)>128){strlen=strlen+2;}else{strlen=strlen+1;}
if(strlen>len){return str.substring(0,i)+(text?text:"");}}
return str;};jobcn.util.isEmpty=function(value){if(jobcn.util.trim(value)==""){return true;}
return false;};jobcn.util.isDate=function(str){if(str==null||str=='')return false;re=/\d{4}-{1}\d{2}-{1}\d{2}$/;return str.match(re);};jobcn.util.isNumeric=function(str){strRef="1234567890";if(str=="")return false;for(i=0;i<str.length;i++){tempChar=str.substring(i,i+1);if(strRef.indexOf(tempChar,0)==-1){return false;}}
return true;};jobcn.util.isFloat=function(str){var re=/^[0-9]+.?[0-9]*$/;return re.test(s);};jobcn.util.isEmail=function(str,separater){if(!str)return false;var res=/^\w+([-+.]{0,6}\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*$/;var re=new RegExp(res);var arr;if(separater)
{arr=str.split(separater);}else{arr=[str]}
for(var i=0;i<arr.length;i++)
{if(arr[i].match(re)==null)
{return false;}}
return true;};jobcn.util.escapeHtml=function(str)
{if(typeof(str)!="string")return str;if(jobcn.util.isEmpty(str))return"";str=str.replaceAll("&","&amp;");str=str.replaceAll("\"","&quot;");str=str.replaceAll(" ","&nbsp;");str=str.replaceAll("<","&lt;");str=str.replaceAll(">","&gt;");str=str.replaceAll("\'","&#039;");str=str.replaceAll("\r\n","<br/>");str=str.replaceAll("\n","<br/>");str=str.replaceAll("\r","<br/>");return str;};jobcn.util.unescapeHtml=function(str)
{if(typeof(str)!="string")return str;if(jobcn.util.isEmpty(str))return"";str=str.replaceAll("&quot;","\"");str=str.replaceAll("&nbsp;"," ");str=str.replaceAll("&lt;","<");str=str.replaceAll("&gt;",">");str=str.replaceAll("&#039;","\'");str=str.replaceAll("<br>","\n");str=str.replaceAll("<br\/>","\n");str=str.replaceAll("&#61;","=");str=str.replaceAll("&amp;","&");return str;};jobcn.util.isFunction=function(obj){if(!obj)return false;return Object.prototype.toString.call(obj)==="[object Function]";};jobcn.util.isArray=function(obj){if(!obj)return false;return Object.prototype.toString.call(obj)==="[object Array]";};jobcn.util.isObject=function(obj){if(!obj)return false;return Object.prototype.toString.call(obj)==="[object Object]";};jobcn.util.cookie={get:function(name){var cookieValue=null;if(document.cookie&&document.cookie!=''){var cookies=document.cookie.split(';');for(var i=0;i<cookies.length;i++){var cookie=(cookies[i]||"").replace(/^(\s|\u00A0)+|(\s|\u00A0)+$/g,"");if(cookie.substring(0,name.length+1)==(name+'=')){var decode=function(s){s=s.replace(/\+/g," ");return decodeURIComponent(s);};cookieValue=decode(cookie.substring(name.length+1));break;}}}
return cookieValue;},set:function(name,value,options){options=options||{};if(value===null){value='';options.expires=-1;}
var expires='';if(options.expires&&(typeof options.expires=='number'||options.expires.toUTCString)){var date;if(typeof options.expires=='number'){date=new Date();date.setTime(date.getTime()+(options.expires*24*60*60*1000));}else{date=options.expires;}
expires='; expires='+date.toUTCString();}
var path='; path='+(options.path||"/");var domain=options.domain?'; domain='+(options.domain):'';var secure=options.secure?'; secure':'';document.cookie=[name,'=',encodeURIComponent(value),expires,path,domain,secure].join('');},remove:function(name){this.set(name,null);}};jobcn.pkg("jobcn.lang");if(!Array.prototype.indexOf){Array.prototype.indexOf=function(substr,start){if(!(this instanceof Array)){return-1;}
var ta,rt,d='\0';if(start!=null){ta=this.slice(start);rt=start;}else{ta=this;rt=0;}
var str=d+ta.join(d)+d,t=str.indexOf(d+substr+d);if(t==-1)return-1;rt+=str.slice(0,t).replace(/[^\0]/g,'').length;return rt;};}
String.prototype.endWith=function(str){if(str==null||str==""||this.length==0||str.length>this.length)
return false;if(this.substring(this.length-str.length)==str)
return true;else
return false;return true;};String.prototype.startWith=function(str){if(str==null||str==""||this.length==0||str.length>this.length)
return false;if(this.substr(0,str.length)==str)
return true;else
return false;return true;};if(!String.prototype.trim){String.prototype.trim=function(){return this.replace(/^\s+/,"").replace(/\s+$/,"");};}
String.prototype.len=function(){return this.replace(/[^\x00-\xff]/g,"aa").length;};String.prototype.replaceAll=function(s1,s2){return this.replace(new RegExp(s1,"gm"),s2);}
String.prototype.parseDate=function(format){var o={"\\.":{v:"\\."},"\\?":{v:"\\?"},"M+":{v:"(0[1-9]|1[0-2]|[1-9])",k:"MM"},"d+":{v:"(3[01]|[12][0-9]|0[1-9]|[1-9])",k:"dd"},"y+":{v:"(\\d{4})",k:"yyyy"},"H+":{v:"(2[0-3]|[01][0-9]|[0-9])",k:"HH"},"m+":{v:"([0-5][0-9]|[0-9])",k:"mm"},"s+":{v:"([0-5][0-9]|[0-9])",k:"ss"},"S":{v:"(\\d+)",k:"S"}};var index=[];var fmt=format;var p;var tmp;for(var k in o){if((p=format.search(new RegExp("("+k+")")))!=-1){tmp=o[k];fmt=fmt.replace(RegExp.$1,tmp.v);if(tmp.k)index.push({n:tmp.k,order:p})}}
index.sort(function(a,b){return a.order-b.order;});tmp={};for(var i=0;i<index.length;i++)tmp[index[i].n]=i+1;var r=this.match(new RegExp(fmt));if(!r){throw"Invalid String for parse to Date!";}
var d=new Date();if(tmp.yyyy)d.setFullYear(r[tmp.yyyy]);if(tmp.dd){var dd=r[tmp.dd];d.setDate(dd);d.setDate(dd);}else{d.setDate(1);d.setDate(1);}
if(tmp.MM)d.setMonth(r[tmp.MM]-1);if(tmp.HH)d.setHours(r[tmp.HH]);else d.setHours(0);if(tmp.mm)d.setMinutes(r[tmp.mm]);else d.setMinutes(0);if(tmp.ss)d.setSeconds(r[tmp.ss]);else d.setSeconds(0);if(tmp.S)d.setMilliseconds(r[tmp.S]);else d.setMilliseconds(0);return d;};Date.prototype.format=function(fmt){var o={"M+":this.getMonth()+1,"d+":this.getDate(),"h+":this.getHours()%12==0?12:this.getHours()%12,"H+":this.getHours(),"m+":this.getMinutes(),"s+":this.getSeconds(),"q+":Math.floor((this.getMonth()+3)/3),"S":this.getMilliseconds()};var week={"0":"\u65e5","1":"\u4e00","2":"\u4e8c","3":"\u4e09","4":"\u56db","5":"\u4e94","6":"\u516d"};if(/(y+)/.test(fmt)){fmt=fmt.replace(RegExp.$1,(this.getFullYear()+"").substr(4-RegExp.$1.length));}
if(/(E+)/.test(fmt)){fmt=fmt.replace(RegExp.$1,((RegExp.$1.length>1)?(RegExp.$1.length>2?"\u661f\u671f":"\u5468"):"")+week[this.getDay()+""]);}
for(var k in o){if(new RegExp("("+k+")").test(fmt)){fmt=fmt.replace(RegExp.$1,(RegExp.$1.length==1)?(o[k]):(("00"+o[k]).substr((""+o[k]).length)));}}
return fmt;};if(!0&&window.JSON&&window.JSON.parse&&window.JSON.stringify){jobcn.lang.json=(function(){var A=/___$/;return{parse:function(str){try{return window.JSON.parse(str)}catch(e){return false}},stringify:function(str){try{return window.JSON.stringify(str,function(E,D){return!A.test(E)?D:null})}catch(e){return null}}}})()}else{jobcn.lang.json=function(){function f(n){return n<10?"0"+n:n}
Date.prototype.toJSON=function(){return[this.getUTCFullYear(),"-",f(this.getUTCMonth()+1),"-",f(this.getUTCDate()),"T",f(this.getUTCHours()),":",f(this.getUTCMinutes()),":",f(this.getUTCSeconds()),"Z"].join("")};var m={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"};function stringify(value){var a,i,k,l,r=/["\\\x00-\x1f\x7f-\x9f]/g,v;switch(typeof value){case"string":return r.test(value)?'"'+value.replace(r,function(a){var c=m[a];if(c){return c}
c=a.charCodeAt();return"\\u00"+Math.floor(c/16).toString(16)+(c%16).toString(16)})+'"':'"'+value+'"';case"number":return isFinite(value)?String(value):"null";case"boolean":case"null":return String(value);case"object":if(!value){return"null"}
a=[];if(typeof value.length==="number"&&!value.propertyIsEnumerable("length")){l=value.length;for(i=0;i<l;i+=1){a.push(stringify(value[i])||"null")}
return"["+a.join(",")+"]"}
for(k in value){if(k.match("___$")){continue}
if(value.hasOwnProperty(k)){if(typeof k==="string"){v=stringify(value[k]);if(v){a.push(stringify(k)+":"+v)}}}}
return"{"+a.join(",")+"}"}}
return{stringify:stringify,parse:function(text){if(/^[\],:{}\s]*$/.test(text.replace(/\\["\\\/b-u]/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,""))){return eval("("+text+")")}
return false}}}()}
jobcn.pkg("jobcn.form.input");jobcn.form.input.watermark=function(selector,text,options){if(!text)
{throw("Please set watermark text!");return;}
var $=jQuery;options=$.extend(true,{},{color:"#999",form:null},options);$(selector).each(function(){var thix=$(this);var blur=function(){if($.trim(thix.attr("value"))==""||$.trim(thix.attr("value"))==text)
{thix.attr("value",text);thix.css("color",options.color);}};var focus=function(){var value=$.trim(thix.attr("value"));if(value==""||value==text)
{thix.attr("value","");}
thix.css("color","#000");};thix.bind("focus",focus).bind("blur",blur);blur();if(!options.form){}else{$(options.form).submit(function(){if(thix.val()==text)thix.val("");});}});};(function(){var wordCountDefaultOptions={max:Number.MAX_VALUE,exceedCallback:null},count=function(val){var allLen=val.length,enLen=val.replace(/[^\x00-\xff]/g,"").length,inputLength=(enLen%2==0?enLen/2:parseInt(enLen/2)+1)+(allLen-enLen);return inputLength;};jobcn.form.input.wordCount=function(selector,callback,options){var $=jQuery,isArray=$.isArray(options);$(selector).each(function(i){var opt=isArray?options[i]:options;opt=$.extend({},wordCountDefaultOptions,opt);if(typeof(callback)=="function"){callback.call(this,count(this.value));}else{$(callback).eq(i).html(count(this.value));}
$(this).bind("keyup",function(){var inputLength=count(this.value);if(inputLength>opt.max){if(opt.exceedCallback){opt.exceedCallback();}}
if(typeof(callback)=="function"){callback.call(this,inputLength);}else{$(callback).eq(i).html(inputLength);}});});};})();jobcn.pkg("jobcn.form.validator");(function(){var _warn=function(method,msg){if(logger&&logger.warn)logger.warn(method,msg);};var _error=function(method,msg){if(logger&&logger.error)logger.error(method,msg);};var attr=(function(){if(!window.$){return"attr";}else{return $.fn.prop?"prop":"attr";}})()
var _default={allowEmpty:true,async:true};var _validator={};var _verifier={};var _vaildOne=function(value,obj,options,type,rule,outOption){jQuery.extend(outOption,options);if(type)
{rule=_verifier[type];if(!rule)
{_warn(type+" rule is undefined!");return true;}}
var r;if(type)outOption.type=type;if(rule.length==3)
{r=rule(value,obj,outOption);}else{r=rule(value,outOption);}
if(!r)
{if(outOption.errorFunction){var f=function(){outOption.errorFunction(obj||value,outOption);};if(options.async)
{setTimeout(f,1);}else f();}
return false;}
return true;};var _validOneTarget=function(value,obj,options,outOption){if(!options.type)
{if(!_vaildOne(value,obj,options,null,options.rule,outOption))return false;}else{var types=options.type;if(typeof(options.type)=="string")types=[options.type];var _v={};for(var j=0;j<types.length;j++)
{if(!_v[types[j]])
{if(!_vaildOne(value,obj,options,types[j],null,outOption))return false;_v[types[j]]=1;}}}
return true;};var _validAll=function(obj){var _tid=obj.attr("validator");if(!_tid)return true;var _vactions=_validator[_tid];var _value;switch(obj[attr]("tagName")){case"SELECT":_value=obj.val();break;default:_value=obj[0].value;}
var _v={};var outOptions=[];for(var i=0;i<_vactions.length;i++)
{var outOption={};if(!_validOneTarget(_value,obj,_vactions[i],outOption)){return false;}
outOptions.push(outOption);}
for(var i=0;i<_vactions.length;i++)
{var options=_vactions[i];if(options.successFunction)
{if(options.async)
{var opt=outOptions[i];setTimeout(function(){options.successFunction(obj||_value,opt);},1);}else{options.successFunction(obj||_value,outOptions[i]);}}}
return true;};jobcn.form.validator=function(arg1,arg2){if(typeof(arg2)=="object")
{var outOption={};if(_validOneTarget(arg1,null,arg2,outOption)&&arg2.successFunction)
{if(arg2.async)
{setTimeout(function(){arg2.successFunction(arg1,outOption);},1);}else{arg2.successFunction(arg1,outOption);}}
return;}
var selector=arg1,stopWhenError=arg2;var s=jQuery(selector);var tag=s[attr]("tagName");stopWhenError=(typeof(stopWhenError)=="boolean"?stopWhenError:true);switch(tag){case"SELECT":case"INPUT":case"TEXTAREA":return _validAll(s);}
var s2=s.find("select[validator],input[validator],textarea[validator]");var result=true;for(var i=0;i<s2.length;i++)
{if(!_validAll(jQuery(s2[i])))
{if(stopWhenError)
{return false;}else{result=false;}}}
return result;};jobcn.form.validator.register=function(type,fun){_verifier[type]=fun;};jobcn.form.validator.get=function(type){return _verifier[type];};var ramcode=0;jobcn.form.validator.bind=function(selector,arr){if(!jobcn.util.isArray(arr))arr=[arr];var vids=[];var objs=jQuery(selector);for(var i=0;i<objs.length;i++)
{var obj=jQuery(objs[i]);var vid=obj.attr("validator");if(!vid)
{vid="validator"+(++ramcode)+(new Date()).getTime();obj.attr("validator",vid);}
if(!_validator[vid])_validator[vid]=[];for(var j=0;j<arr.length;j++)
{arr[j]=jQuery.extend({},_default,arr[j]);_validator[vid].push(arr[j]);}
vids.push(vid);}
return vids;};var $JFV=jobcn.form.validator;$JFV.register("regex",function(str,options){if(options.allowEmpty&&jobcn.util.isEmpty(str))return true;if(!options.regex)
{_error("regex","need parameter of 'regex'!");return false;}
return options.regex.test(str);});var contentRegExp=/([\`\~\!\@\#\$\^\&\*\(\)\+\-\=\|\{\}\'\:\;\"\,\[\]\.\<\>\/\?\n\r\t～！￥……*（）——|『』【】‘；“。，、？ ])/g;$JFV.register("invalid",function(str,options){str=str.replace(contentRegExp,"");return!(str.length===0);});$JFV.register("repeat",function(str,options){str=str.replace(contentRegExp,"");if(jobcn.util.isEmpty(str))return true;var _startNum=3;var _firstStr=str.substring(0,2);var _regFirst=new RegExp("^("+_firstStr+"){3,}","g");if(_regFirst.test(str)){return false;}
if(str.length<10)return true;if(str.length>20){_firstStr=str.substring(0,5);_startNum=5;}else{_firstStr=str.substring(0,_startNum);}
var _endIndex=str.substr(_startNum,str.length-_startNum).indexOf(_firstStr);if(_endIndex!==-1){var _repeatStr=str.substr(_startNum,_endIndex+_startNum);var _regRepeat=new RegExp(_repeatStr,"g");var _result=str.match(_regRepeat);if(_result&&_result.length>1){return false;}}
return true;});$JFV.register("require",function(str,options){options.allowEmpty=false;return!jobcn.util.isEmpty(str);});$JFV.register("email",function(str,options){if(options.allowEmpty&&jobcn.util.isEmpty(str))return true;var separater=null;if(options.separater){separater=options.separater;}
return jobcn.util.isEmail(str,separater);});$JFV.register("eq",function(str,options){if(!options.compareTo)
{_error("eq","need parameter of 'compareTo'!");return false;}
var str2=jQuery(options.compareTo).val();if(!options.format)
{return str==str2;}
var vdate=$JFV.get("date");if(!(vdate(str,options)&&vdate(str2,options)))return false;return str.parseDate(options.format).getTime()==str2.parseDate(options.format).getTime();});$JFV.register("lt",function(str,options){if(options.allowEmpty&&jobcn.util.isEmpty(str))return true;if(!options.compareTo)
{_error("lt","need parameter of 'compareTo'!");return false;}
var str2=jQuery(options.compareTo).val();if(!options.format)
{options.negative=true;var vfloat=$JFV.get("float");if(!vfloat(str,options))return false;if(!vfloat(str2,options))return false;str=parseFloat(str);str2=parseFloat(str2);return str<str2;}
var vdate=$JFV.get("date");if(!(vdate(str,options)&&vdate(str2,options)))return false;return str.parseDate(options.format)<str2.parseDate(options.format);});$JFV.register("le",function(str,options){var eq=$JFV.get("eq");var lt=$JFV.get("lt");return eq(str,options)||lt(str,options);});$JFV.register("gt",function(str,options){if(options.allowEmpty&&jobcn.util.isEmpty(str))return true;if(!options.compareTo)
{_error("gt","need parameter of 'compareTo'!");return false;}
var str2=jQuery(options.compareTo).val();if(!options.format)
{options.negative=true;var vfloat=$JFV.get("float");if(!vfloat(str,options))return false;if(!vfloat(str2,options))return false;str=parseFloat(str);str2=parseFloat(str2);return str>str2;}
var vdate=$JFV.get("date");if(!(vdate(str,options)&&vdate(str2,options)))return false;return str.parseDate(options.format)>str2.parseDate(options.format);});$JFV.register("ge",function(str,options){var eq=$JFV.get("eq");var gt=$JFV.get("gt");return eq(str,options)||gt(str,options);});$JFV.register("length",function(str,options){if(options.allowEmpty&&jobcn.util.isEmpty(str))return true;if(!(options.min||options.max))
{_error("length","need parameter of 'min' or 'max'!");return false;}
var allLen=str.length,enLen=str.replace(/[^\x00-\xff]/g,"").length,inputLength=(enLen%2==0?enLen/2:parseInt(enLen/2)+1)+(allLen-enLen),len=inputLength;if(options.min&&len<options.min)return false;if(options.max&&len>options.max)return false;return true;});$JFV.register("intlength",function(str,options){if(options.allowEmpty&&jobcn.util.isEmpty(str))return true;if(!(options.min||options.max))
{_error("intlength","need parameter of 'min' or 'max'!");return false;}
var len=str.replace(/[^\x00-\xff]/g,"aa").length;if(options.min&&len<options.min)return false;if(options.max&&len>options.max)return false;return true;});$JFV.register("range",function(str,options){if(options.allowEmpty&&jobcn.util.isEmpty(str))return true;if(!(options.min||options.max))
{_error("range","need parameter of 'min' or 'max'!");return false;}
options.negative=true;var vfloat=$JFV.get("float");if(!vfloat(str,options))return false;var v=parseFloat(str);if(options.min&&v<options.min)return false;if(options.max&&v>options.max)return false;return true;});$JFV.register("chinese",function(str,options){if(options.allowEmpty&&jobcn.util.isEmpty(str))return true;options.regex=/^[\u4E00-\u9FA5]$/;return $JFV.get("regex")(str,options);});$JFV.register("int",function(str,options){if(options.allowEmpty&&jobcn.util.isEmpty(str))return true;if(options.negative)
{options.regex=/^[-]?\d+$/;}else{options.regex=/^\d+$/;}
return $JFV.get("regex")(str,options);});$JFV.register("float",function(str,options){if(options.allowEmpty&&jobcn.util.isEmpty(str))return true;if(options.negative)
{options.regex=/^[-]?\d+(\.\d+)?$/;}else{options.regex=/^\d+(\.\d+)?$/;}
return $JFV.get("regex")(str,options);});$JFV.register("date",function(str,options){if(options.allowEmpty&&jobcn.util.isEmpty(str))return true;if(!options.format)
{_warn("date","need parameter of 'format'!");return false;}
var o={"\\.":"\\.","M+":"(0[1-9]|[1-9]|1[0-2])","d+":"(0[1-9]|[1-9]|[12][0-9]|3[01])","y+":"(\\d{4})","H+":"([0-9]|[01][0-9]|2[0-3])","m+":"([0-9]|[0-5][0-9])","s+":"([0-9]|[0-5][0-9])","S":"(\\d+)"};var fmt=options.format;for(var k in o){if(new RegExp("("+k+")").test(options.format)){fmt=fmt.replace(RegExp.$1,o[k]);}}
options.regex=new RegExp("^"+fmt+"$");if(!$JFV.get("regex")(str,options))return false;return str==str.parseDate(options.format).format(options.format);});$JFV.register("url",function(str,options){if(options.allowEmpty&&jobcn.util.isEmpty(str))return true;if(str.startWith("http://")){str=str.substring(7);}else if(str.startWith("https://")){str=str.substring(8);}else{if(options.requireProtocol)return false;}
if(!str)return false
options.regex=/^[A-Za-z0-9]+\.[A-Za-z0-9]+[\/=\?%\-&_~`@[\]\':+!]*([^<>\"\"])*$/;return $JFV.get("regex")(str,options);});})();jobcn.Plugin.if_jquery(function($){jobcn.Plugin.if_jsapi(function(jobcn){jobcn.loader._queue["jquery.bgiframe"]={status:"complete"};});$.fn.bgiframe=($.browser.msie&&/msie 6\.0/i.test(navigator.userAgent)?function(s){s=$.extend({top:'auto',left:'auto',width:'auto',height:'auto',opacity:true,src:'javascript:false;'},s);var html='<iframe class="bgiframe"frameborder="0"tabindex="-1"src="'+s.src+'"'+'style="display:block;position:absolute;z-index:-1;'+
(s.opacity!==false?'filter:Alpha(Opacity=\'0\');':'')+'top:'+(s.top=='auto'?'expression(((parseInt(this.parentNode.currentStyle.borderTopWidth)||0)*-1)+\'px\')':prop(s.top))+';'+'left:'+(s.left=='auto'?'expression(((parseInt(this.parentNode.currentStyle.borderLeftWidth)||0)*-1)+\'px\')':prop(s.left))+';'+'width:'+(s.width=='auto'?'expression(this.parentNode.offsetWidth+\'px\')':prop(s.width))+';'+'height:'+(s.height=='auto'?'expression(this.parentNode.offsetHeight+\'px\')':prop(s.height))+';'+'"/>';return this.each(function(){if($(this).children('iframe.bgiframe').length===0)
this.insertBefore(document.createElement(html),this.firstChild);});}:function(){return this;});$.fn.bgIframe=$.fn.bgiframe;function prop(n){return n&&n.constructor===Number?n+'px':n;}});jobcn.Plugin.if_jquery(function($){$.fn.check=function(type){switch(type)
{case true:return this.each(function(){this.checked=true;});break;case false:return this.each(function(){this.checked=false;});break;default:return this.each(function(){this.checked=!this.checked;});}}
$.fn.select=function(value){return this.each(function(){$(this).val(value);});}});