define('widge.fileUploader',function(require,exports,module){var $=module['jquery'],util=require('base.util'),shape=module['base.shape'],doc=document,win=window;var fileUploader=shape(function(o){fileUploader.parent().call(this,util.merge({trigger:$('#fileBtn'),fileName:'Filedata',fileExt:'.jpg,.png',maxSize:52100,isMutilple:true,domain:'',uploadURL:'/api/web/uploadify.api',imageURL:'http://upload.abc.com/CompanyImages/TempTemplateImage/',uploadData:{act:'companyTemplate'},totalParam:'Count',progressURL:null,isRepeat:true,buttonClass:'ui_upload',fileInputClass:'ui_upload_btn',urlParam:null,max:9999},o));this.init();});var uid=0;function creatProgressID(){return'progres-'+(++uid);}
fileUploader.template={file:function(className,file,id){return['<input class= "'+className+'" type="file" ','size="100" name="'+file+'" ','id="'+file+'" ','data-progressID="'+id+'" />'].join('');},hidden:function(name,val){return'<input type="hidden" value="'+val+'" name="'+name+'" />';},iframe:function(name){return['<iframe id="'+name+'" name="'+name+'" width="0" height="0" frameborder="0" style="display:none;">','</iframe>'].join('')},form:function(url,name){return['<form action="'+url+'" target="'+name+'" method="post" ','enctype="multipart/form-data" style="display:none;"></form>'].join('')}}
fileUploader.implement({init:function(){var trigger=this.get('trigger');if(!(trigger&&!util.type.isString(trigger)&&trigger[0])){return;}
this._contNumber=0;this._uploading=false;this._queue=[];this._queueFile={};this._fileCache={};this._render();this._createFile();},_render:function(){this.get('buttonClass')&&this.get('trigger').addClass(this.get('buttonClass'));},_createFile:function(){this.progressID=creatProgressID();if(this.buttonFile){this.buttonFile.off('change');this.buttonFile.remove();}
this.buttonFile=$(fileUploader.template.file(this.get('fileInputClass'),this.get('fileName'),this.progressID)).appendTo(this.get('trigger'));var self=this;this.buttonFile.on('change',function(e){var file=$(this).val();e.url=file;self.trigger('select',e);if(!self.isFileExt(file)){alert('不允许上传此类型文件');return;}
if(!self.get('isRepeat')&&self._fileCache[file]){alert('当前文件已经存在！');return;}
if(!self.get('isMutilple')&&self._uploading){alert('不容许多个文件同时上传');return;}
if(!self.get('max')){self.buttonFile&&self.buttonFile.hide();alert("上传文件数量不能超过"+self.get('max')+"个");self._createFile();return false;}
self._fileCache[file]=1;self._fileCache[self.progressID]=file;self.trigger('startUpload',e);self._onProgresreading();});},_onProgresreading:function(){var self=this,max=this.get('max'),progressID=this.progressID,e={};if(util.type.isBoolean(max)){this.set('max',max-1);}
e.target=this.buttonFile;e.id=this.progressID;var value=e.url=this.buttonFile.val();if(this._queue.length){this.trigger('progressReadQueue',e);this.queue.push({progressID:this.progressID,file:this.buttonFile});return this._createFile();}else if(this._uploading){return false;}
this._queueFile[value]=true;value.indexOf('\\')<0?value:value.substring(value.lastIndexOf('\\')+1);this.trigger('progressReading',e);if(!this._uploading){this._createFormIFrame();this.buttonFile.appendTo(this._form);this._uploading=true;this._nowProgressID=progressID;if(this.get('uploadData')){$.each(this.get('uploadData'),function(name,val){self._form.prepend(fileUploader.template.hidden(name,val));});}
this._form.prepend(fileUploader.template.hidden(this.get('totalParam'),this.get('maxNumber')));try{this._form.submit();}catch(e){alert('请用IE6以上浏览器传附件!');}
this.get('progressURL')&&this._onProgressstart(progressID);}
this._createFile();},_onProgresstart:function(progressID){var self=this,startTime=new Date;this._progresNumber=0;this._nocancel=true;(function(){var callee=arguments.callee,url,type;if(self.get('progressURL').indexOf(win.location.host)==-1){url=self.get('progressURL')+'?X-Progress-ID='+progressID+'&jsonpcallback=?';type='jsonp';}else{url=self.get('progressURI')+'?X-Progress-ID='+progressID;type='get';}
$.ajax({url:url,type:type,dataType:'json',success:function(e){if(!self._nocancel)
return;if(e.state=='uploading'){if(parseFloat(e.received)>=parseFloat(e.size)){self._onProgresing(99,100,progressID);self._uploading=false;}else{self._onProgresing(parseFloat(e.received),parseFloat(e.size),progressID);}
if(++self._progresNumber==1){self._progresstime=(+new Date)-startTime;}
self._uploading&&callee();}else if(e.state=='done'){self._uploading=false;}else{setTimeout(function(){self._uploading&&callee();},2000);}}});})();},_onProgresing:function(uploaded,total,progressID,time){var e={progress:progressID,target:this.buttonFile,value:this.buttonFile.val()}
if(this._progresNumber==1){if(this.get('maxSize')*1024<total){alert('上传尺寸超过最大值:'+(this.get('maxSize')/1024)+'M');this.trigger('progressError',e);this._uploading=false;return this._onCancelUpload(progressID);}}
e.uploaded=uploaded;e.total=total;e.time=time||this._progressTime||1000;this.trigger('progressing',e);},_onProgresed:function(url,e){var self=this,obj={progressID:this._nowProgressID,url:url,data:e,target:this.buttonFile};this._removeFormIFrame();if(this._progresNumber==0){this._onProgresing(Math.random(),1,this._nowProgressID,1000);(function(nowProgressID,url){setTimeout(function(){self.trigger('progresed',obj);self._uploading=false;self._progresNumber=0;},1000);})(this._nowProgressID,url);}else{this.trigger('progresed',obj);self._uploading=false;self._progresNumber=0;}},_onCancelUpload:function(progressID){for(var len=this._queue.length-1;len>=0;len--){if(this._queue[len].progressID==progressID){this._queue.splice(len,1);}}
delete this._fileCache[this._fileCache[progressID]];var max=this.get('max');if(typeof(max)!="boolean"){this.set('max',max+1);}
if(this._nowProgressID==progressID){this._nocancel=false;this._removeFormIFrame();this.trigger('cancelUpload',{progress:progressID,target:this.buttonFile,url:this.buttonFile.val()});this._uploading=false;this._progresNumber=0;this._uploadQueue();}},_onProgressError:function(url,e){this.trigger('progressError',{progress:this._nowProgressID,data:e,url:url,target:this.buttonFile});},_uploadQueue:function(){if(this._queue.length){var shift=this._queue.shift(),self=this;this._createFormIFrame();this._form.attr('action',this._form.attr('action').replace(/(X-Progress-ID=)([0-9.]+)$/,'$1'+shift.progressID));shift.file.appendTo(this.form);$.each(this.get('uploadData'),function(name,value){self._form.prepend(fileUploader.template.hidden(name,val));});this._form.prepend(fileUploader.template.hidden(this.get('totalParam'),this.get('max')));this.trigger('progressReading',{progress:shift.progressID,url:shift.file.val(),target:this.buttonFile});this._uploading=true;setTimeout(function(){self._nowProgressID=shift.progressID;self._form.submit();},100);this.options.progressURL&&this._onProgresstart(shift.progressID);}},_createFormIFrame:function(){if(!this._iframe){var name='uploadpRrogress_'+(+new Date),self=this;var domain='',callback=this.callback='uploadSuccess'+(+new Date);if(this.get('domain')&&doc.domain.indexOf(this.get('domain'))>-1){doc.domain=this.get('domain');domain='domain='+doc.domain;}
var url=this.get('uploadURL');this._iframe=$(fileUploader.template.iframe(name)).appendTo(doc.body);this._form=$(fileUploader.template.form(url,name)).appendTo(doc.body);this._getResponse(function(e){self._uploading=false;self._removeFormIFrame();var url=self.get('param')?e[self.get('param')]:self.get('imageURL')+e.fileName;if(e.status==1){self._onProgresed(url,e);}else{self._onProgressError(url,e);}
self._uploadQueue();});}},_getResponse:function(func){var self=this,iframe=this._iframe[0],response;this._iframe.on('load',function(){var idoc=iframe.contentDocument?iframe.contentDocument:win.frames[iframe.id].document;if(idoc.readyState&&idoc.readyState!='complete'){return;}
if(idoc.body&&idoc.body.innerHTML=="false"){return;}
if(idoc.XMLDocument){response=idoc.XMLDocument;}else if(idoc.body){response=idoc.body.innerHTML;if(idoc.body.firstChild&&idoc.body.firstChild.nodeName.toUpperCase()=='PRE'){response=idoc.body.firstChild.firstChild.nodeValue;}
if(response){response=eval("("+response+")");}else{response={};}
if(idoc.body.firstChild.nodeName.toUpperCase()=='PRE'){response=idoc.body.firstChild.firstChild.nodeValue;}}else{response=idoc;}
func.call(self,response);});},_removeFormIFrame:function(){if(this._iframe){this._iframe.remove();this._form.remove();this._iframe=this._form=null;}},_refreshNum:function(num){var max=this.get('max');if(typeof(max)!="boolean"){this.set('max',num||max+2);}
if(this.get('max')>=1){this.buttonFile&&this.buttonFile.show();}},isFileExt:function(file){var fileExt=file.substring(file.lastIndexOf('.'),file.length).toLowerCase();if(this.get('fileExt').indexOf(fileExt)==-1){return false;}
return true;},destory:function(){this.buttonFile.off('change').remove();this._removeFormIFrame();fileUploader.parent('destory').call(this);}});return fileUploader;});